### ISSUE TITLE
bug: problema con i permessi

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#31]
correlato a #19

Ciao!

Eseguo il docker container in TrueNas SCALE che utilizza Kubernetes, il problema dei permessi è serio.
Per eseguire correttamente il container devo eseguirlo come utente root che espone diverse problematiche, oltre a quelle di sicurezza anche il fatto che il file che viene generato e spostato ha dei permessi sfalsati.

Per risolvere il problema ho impostato manualmente l'ownership della cartella scripts, ma essendo che eseguo il container attraverso Kubernetes se si riavvia il pod cambia il container ID e quindi la modifica effettuata.

Sarebbe comodo e ottimale la possibilità di impostare tramite settings env user id e group id.

potrebbe essere comodo eseguire uno script che crea un utente X (chiamato come vuoi, ad esempio nome del progetto o qualsiasi cosa) che ha come id l'id passato nell env. (Simile a quello che avviene nei containers di linuxserver.io

esempio:
https://github.com/linuxserver/docker-openssh-server/blob/master/root/etc/cont-init.d/10-adduser

**Comment by MainKronos** [comment]
Grazie per la segnalazione. Avevo intenzione di correggerlo ma vista la mia pigrizia l'avevo sempre rimandato e poi alla fine me ne sono pure dimenticato😅. Lo sistemerò sicuramente per la prossima release.

**Comment by MainKronos** [comment]
Dovrei aver risolto il problema con i permessi con la versione `1.5.0`, appena puoi dimmi se così può andare.

**Comment by Simoneu01** [comment]
OK sicuramente un grande passo avanti, adesso posso eseguire il container non come root.

Ultima sarebbe ideale permettere la definizione dei permessi da impostare alla cartella quando viene creata dallo script e non da me o da sonarr.

**Comment by MainKronos** [comment]
finalmente risolto con la [`1.8.1`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.8.1) 🎉😂

**Comment by berta24** [comment]
> finalmente risolto con la [`1.8.1`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.8.1) 🎉😂

ho aggiornato solo oggi e mi ritrovo questo errore:
`GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14f7f8a7ea60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/animeworld/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14f7f8a7ed90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/animeworld/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14f7f8a7ee80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/animeworld/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14f7f8aa91f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/animeworld/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14f7f8aa93a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/animeworld/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14754d4678b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.animeworld.tv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14754d4678b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/script/main.py", line 12, in <module>
    from anime_downloader import job
  File "/script/anime_downloader/__init__.py", line 4, in <module>
    import animeworld as aw
  File "/usr/local/lib/python3.9/site-packages/animeworld/__init__.py", line 4, in <module>
    from .utility import find
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 151, in <module>
    SES = MySession() # sessione contenente Cookie e headers
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 23, in __init__
    self.fixCookie()
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 30, in fixCookie
    res = self.get("https://www.animeworld.tv")
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.animeworld.tv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14754d4678b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

** Press ANY KEY to close this window ** `


Sinceramente non capisco da cosa sia causato, ho cambiato anche PUID e PGID

**Comment by Simoneu01** [comment]
Avendo aggiunto queste righe di codice nel dockerfile è impossibile avviare il docker da utente non root, in quanto groupadd richiedere i permessi privilegiati 
```
RUN groupadd --gid 1000 dockeruser
RUN useradd --no-log-init -r -m --gid dockeruser --uid 1000 dockeruser 
```

**Comment by Simoneu01** [comment]
Sto avviando come root il docker ma ottengo questo errore: 
`groupmod: cannot lock /etc/group; try again later.`

**Comment by Simoneu01** [comment]
ho creato un docker di test senza il groupmod che viene effettuato nello script e così riesco ad avviarlo:
(https://github.com/MainKronos/Sonarr-AnimeDownloader/compare/main...Simoneu01:Sonarr-AnimeDownloader:test)

**Comment by MainKronos** [comment]
Vedo di risolvere il problema quanto prima.

**Comment by MainKronos** [comment]
Errore risolto in [`dev`](https://github.com/MainKronos/Sonarr-AnimeDownloader/tree/dev), verrà poi rilasciato nella prossima release a breve
